import DefaultLayout from "@/components/Layout/DefaultLayout";
import { Footer } from "@/components/Organisms/Footer/footer";
import { Header1 } from "@/components/Organisms/Header/Header";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import React from "react";
import "./globals.css";

const raleway = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Majalah Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <span className="grid-cols-12 sticky top-0 z-50 backdrop-blur-xl">
          <Header1 />
        </span>
        <DefaultLayout>{children}</DefaultLayout>
        <Footer />
      </body>
    </html>
  );
}
